apiVersion: apps/v1
kind: Deployment
metadata:
  name: moevm-anti-plag
spec:
  replicas: 3
  selector:
    matchLabels:
      app: moevm-anti-plag
  template:
    metadata:
      labels:
        app: moevm-anti-plag
    spec:
      containers:
      - name: moevm-anti-plag
        image: moevm-anti-plag:1.0
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
