apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: moevm-anti-plag-ingress
  labels:
    app.kubernetes.io/name: moevm-anti-plag-ingress
spec:
  rules:
  - host: anti-plag.ru
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: moevm-anti-plag-service
            port: 
              number: 80
