apiVersion: v1
kind: Service
metadata:
  name: {{.Values.names.server_service}}
spec:
  selector:
    app: {{.Values.names.server}}
  ports:
  - protocol: TCP
    name: bolt
    port: 80
    targetPort: {{.Values.ports.server_port}}
  type: ClusterIP