apiVersion: apps/v1
kind: Deployment
metadata:
  name: moevm-anti-plag
spec:
  replicas: 3
  selector:
    matchLabels:
      app: moevm-anti-plag
  template:
    metadata:
      labels:
        app: moevm-anti-plag
    spec:
      containers:
      - name: moevm-anti-plag

        image: spookich1337/anti-plag:latest
        imagePullPolicy: Always

        env: 
        - name: NEO4J_URI
          value: "bolt://moevm-anti-plag-db-service:7687"
        - name: NEO4J_USER
          value: "neo4j"
        - name: NEO4J_PASSWORD
          value: "password123"

        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "256Mi"
            cpu: "500m"

        ports:
        - containerPort: 8080

        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 30

        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 30
