apiVersion: v1
kind: Service
metadata:
  name: moevm-anti-plag-service
spec:
  selector:
    app: moevm-anti-plag
  ports:
  - protocol: TCP
    name: bolt
    port: 80
    targetPort: 8080
  type: ClusterIP